#include <aoc2025lib/day07.hpp>
#include <catch2/catch_test_macros.hpp>

namespace input {
static constexpr auto test =
    R"(.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
)";
}

using namespace aoc2025::day07;

TEST_CASE("parts", "[day07]") {
  STATIC_CHECK(part01(input::test) == 21);
  STATIC_CHECK(part02(input::test) == 40);
}
TEST_CASE("dims", "[day07]") {
  STATIC_CHECK(width(input::test) == 15);
  STATIC_CHECK(height(input::test) == 16);
}
